// Generated by npm run fingerprint. Source paths and hashes: SOURCE_MANIFEST.json.
export const BUILD_INFO = Object.freeze({"version":"1.0.0","sourceSHA256":"6957d5ea277c84b18ae972441b386c2dd6a83ff03b81d34e3941f95f6ec3e2d3"});
