// Generated by npm run fingerprint. Source paths and hashes: SOURCE_MANIFEST.json.
export const BUILD_INFO = Object.freeze({"version":"1.0.0","sourceSHA256":"41a7541cb89bc958f74d9d6b897d88132e72fb8ecdafe377b10b815046db7c76"});
