// Generated by npm run fingerprint. Source paths and hashes: SOURCE_MANIFEST.json.
export const BUILD_INFO = Object.freeze({"version":"1.0.0","sourceSHA256":"7449e43a64418a9ea34f032a2904fbeba64032c5b73bb7f50c5557584084dbb3"});
