#!/usr/bin/env node
/** Fingerprint source inputs, not mutable data, reports, documentation, or this generated build record. */
import {readdir, readFile, writeFile} from 'node:fs/promises';
import {resolve, relative, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const files = [];
async function walk(path) {
  for (const entry of await readdir(path, {withFileTypes:true})) {
    if (entry.name === '__pycache__') continue;
    const full = resolve(path, entry.name);
    if (entry.isDirectory()) await walk(full); else files.push(full);
  }
}
for (const name of ['public','server','migrations','scripts','tests','bench']) await walk(resolve(root,name));
for (const name of ['package.json','package-lock.json','wrangler.jsonc']) files.push(resolve(root,name));
const records = [];
for (const file of files.sort()) {
  const path = relative(root,file).replaceAll('\\','/');
  if (path === 'server/build-info.js' || path.startsWith('bench/results/')) continue;
  const bytes = await readFile(file);
  records.push({path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});
}
records.sort((a,b)=>a.path.localeCompare(b.path));
const sourceSHA256 = createHash('sha256').update(records.map(x=>`${x.sha256}  ${x.path}\n`).join('')).digest('hex');
await writeFile(resolve(root,'SOURCE_MANIFEST.json'),JSON.stringify({formatVersion:1,algorithm:'SHA-256',sourceSHA256,files:records},null,2)+'\n');
await writeFile(resolve(root,'server/build-info.js'),`// Generated by npm run fingerprint. Source paths and hashes: SOURCE_MANIFEST.json.\nexport const BUILD_INFO = Object.freeze(${JSON.stringify({version:'1.0.0',sourceSHA256})});\n`);
console.log(sourceSHA256);
